[project]
name = "present-go-mcp-a2a"
version = "0.1.0"
description = "Comparing Python and Go implementations of MCP and A2A."
readme = "gomcp.slide"
requires-python = ">=3.12"
dependencies = [
    "langchain-ollama>=0.3.7",
]
